version: "3.9"

services: 
  knight:
    build: .
    command: runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    networks: 
      - nginx_network
    
  nginx:
    build: ./nginx
    ports: 
      - 80:80
    networks: 
      - nginx_network

    depends_on: 
      - knight

networks: 
  nginx_network:
    name: nginx_network